### ISSUE TITLE
Multi-account aggregated report

### ISSUE THREAD

**Issue by vfeinman** [awslabs/aws-security-assessment-solution#13]
Prowler doesn't support aggregating a multi-account scan assessment into a single report. This project could attempt to create a single aggregated report.

**Comment by js37** [comment]
Thanks! We plan to use Athena to enable querying across reports. I don't have an ETA yet, but check back for updates.

**Comment by js37** [comment]
We have published an update that includes reporting. Thanks for the feedback.
