### ISSUE TITLE
Increase parallelization by horizontal scaling

### ISSUE THREAD

**Issue by vfeinman** [awslabs/aws-security-assessment-solution#14]
Maybe scale out by creating 2 build projects. One that orchestrates the other and by chunking the multi-account list in groups of three, then start build for each chunk using the MULTI_ACCOUNT_LIST_OVERRIDE environment variable.

**Comment by js37** [comment]
You can change the parallelism by changing PARALLEL_ACCOUNTS in the buildspec. We won't support multiple build projects at this time.

```
#Scan up to three accounts at the same time.
PARALLEL_ACCOUNTS=3
```
