### ISSUE TITLE
Higher account parallelism

### ISSUE THREAD

**Issue by dylanmtaylor** [awslabs/aws-security-assessment-solution#18]
Can we go even higher in parallelism? For customers with ~100+ accounts, the speedup is considerable the more parallelism we have.

**Comment by js37** [comment]
Thanks for the PRs. BUILD_GENERAL1_2XLARGE is not available in GovCloud so I didn't include it. 

Going to XLARGE is considerably more expensive. I will do some more testing to see if we should include it as an option. 

You can always download the template and modify it before deploying.

**Comment by dylanmtaylor** [comment]
> Thanks for the PRs. BUILD_GENERAL1_2XLARGE is not available in GovCloud so I didn't include it.
> 
> Going to XLARGE is considerably more expensive. I will do some more testing to see if we should include it as an option.
> 
> You can always download the template and modify it before deploying.

We actually did this - I am simply sharing my changes back, but you don't have to accept them.

**Comment by dylanmtaylor** [comment]
You know - I bet a XLARGE would be able to do 48 in parallel... this isn't CPU bound so much as RAM, so with significantly higher RAM it shouldn't be an issue. I'm going to edit my PR to skip 24 and do 48 on the XLARGE

**Comment by js37** [comment]
Yeah that was my initial thought as well. Going from large to xlarge is ~4+x the size in CodeBuild

**Comment by dylanmtaylor** [comment]
Yeah, RAM and CPU are roughly 4x the size of the large and the cost is about 4x as high but if it takes 1/4 the time, I think it's worth it for us.

**Comment by js37** [comment]
Fixed in https://github.com/awslabs/aws-security-assessment-solution/pull/19
