### ISSUE TITLE
Template malforms S3 links

### ISSUE THREAD

**Issue by rdoleski87** [awslabs/aws-security-assessment-solution#2]
The latest version of the SelfServiceSec.yml template is malforming S3 links:

 rVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://'
          - !Ref TemplateS3Bucket
          - **'.s3-'**
          - !Ref "AWS::Region"
          - '.amazonaws.com/SelfServiceSecVPC.yml'

It should read:

 rVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://'
          - !Ref TemplateS3Bucket
          - **'.s3.'**
          - !Ref "AWS::Region"
          - '.amazonaws.com/SelfServiceSecVPC.yml'

**Comment by aws-brad** [comment]
We are testing a fix for this issue right now.

**Comment by aws-brad** [comment]
Change pushed to the template.
