### ISSUE TITLE
Feature request: "RunMonthly" variable

### ISSUE THREAD

**Issue by dylanmtaylor** [awslabs/aws-security-assessment-solution#20]
It would be nice to have an easy way to continuously scan and monitor prowler results over time. Monthly feels like a good cadence.

**Comment by js37** [comment]
The AWS Security Assessment Solution is intended to be a point in time snapshot. We don't intend to make this something that runs on any cadence. 

We encourage our customers to use AWS Security Hub or a Partner solution that continuously monitors your adherence to best practices.
