### ISSUE TITLE
Permissions boundaries

### ISSUE THREAD

**Issue by dylanmtaylor** [awslabs/aws-security-assessment-solution#21]
For every role this creates, I would like an easy way to set a custom permissions boundary property. Something like

PermissionsBoundary: 'arn:aws:iam::123xxxxxx789:policy/MyOrganizatoinsPermBoundary'

**Comment by js37** [comment]
I'm going to close this as not on the roadmap. If we get additional signal to prioritize this we may consider in the future. 

Thanks for using SATv2
