### ISSUE TITLE
Option to just use Prowler's native reporting dashboard

### ISSUE THREAD

**Issue by dylanmtaylor** [awslabs/aws-security-assessment-solution#22]
Prowler has a native dashboard. I think it'd be a nice touch if there was a boolean value controlling whether the output is simply copied to s3 unmodified and analysis/database resources would not be created. The user could then download and analyze the output with the prowler native reporting dashboard.

**Comment by js37** [comment]
This is on the roadmap - we plan on addressing this by updating the documentation to demonstrate how to download the S3 objects locally in the correct format so the native dashboard works.

**Comment by js37** [comment]
Fixed in https://github.com/awslabs/aws-security-assessment-solution/commit/3c59d185387f640a18c65915dc92e2d0b2fd10f8
