### ISSUE TITLE
xLambdaCheckFor2k8 fails to create as Lambda function executes with errors

### ISSUE THREAD

**Issue by rdoleski87** [awslabs/aws-security-assessment-solution#3]
The ransomware stack is failing deployment due to the custom resource  **xLambdaCheckFor2k8** failing to create. Per Lambda, the function is failing. This causes the whole solution to fail to deploy.

xLambdaCheckFor2k8:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt rLambdaCheckFor2k8.Arn

**Comment by aws-brad** [comment]
We are having trouble replicating this issue, if you manually run the Lambda function, LambdaCheckFor2k8, what is the error that you see when you use the sample test event "AWS Cloudformation Create Request" and in what region is the function located in?

**Comment by rdoleski87** [comment]
I created a function with the contents of check_for_outdated_os.py, below is the console output:

```
START RequestId: d4288a4e-12b8-4047-9d0e-aaxxxxxxxxxx Version: $LATEST
i-0b2058aaxxxxxxxxxx Ubuntu
i-03d325aaxxxxxxxxxx  Ubuntu
i-09c168aaxxxxxxxxxx  Ubuntu
i-0cf14aaxxxxxxxxxx  Ubuntu
i-0e31b9aaxxxxxxxxxx  Ubuntu
i-0eb3eaaxxxxxxxxxx Ubuntu
i-01d1aaxxxxxxxxxx  Ubuntu
i-048aaaxxxxxxxxxx  Ubuntu
i-04b97aaxxxxxxxxxx Ubuntu
[WARNING]	2020-09-21T17:19:34.405Z	d4288a4e-12b8-4047-aaxxxxxxxxxx 	There are 9 instances that might be running Windows Server 2008.            Consider upgrading them as soon as possible to mitigate Ransomware threats
[WARNING]	2020-09-21T17:19:34.406Z	d4288a4e-12b8-4047-9d0e-aaxxxxxxxxxx 	Instance IDs of the 2008 systems are ['i-0b2058aaxxxxxxxxxx ', 'i-03d325daaxxxxxxxxxx ', 'i-09c1684caaxxxxxxxxxx ', 'i-0cf1aaxxxxxxxxxx ', 'i-0e31b974aaxxxxxxxxxx ', 'i-0eb3eaaaxxxxxxxxxx ', 'i-01d16aaxxxxxxxxxx ', 'i-048aaaaxxxxxxxxxx ', 'i-04aaxxxxxxxxxx ']
[ERROR] TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 105, in lambda_handler
    string = "There are " + COUNT_OF_2008_SYSTEMS +" instances that might be running Windows Server 2008.\END RequestId: d4288a4e-12b8-4047-9d0e-aaxxxxxxxxxx 
REPORT RequestId: d4288a4e-12b8-4047-9d0e-aaxxxxxxxxxx 	Duration: 13309.29 ms	Billed Duration: 13400 ms	Memory Size: 128 MB	Max Memory Used: 87 MB	Init Duration: 427.91 ms
```


**It's a TypeError, seems the variable with the number of instances is not being cast as a string, but instead an int.**

**Also, the instances identified as possibly running 2008 are actually Ubuntu instances.**

I tested in us-east-1

**Comment by aws-brad** [comment]
Thank you for the update, we are taking a look now.

**Comment by aws-brad** [comment]
We have removed the check from the template while we work to address the problem in the functions code.

**Comment by aws-brad** [comment]
The issue was addressed in a patch to the module, thank you for the issue report!
