### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by vyakush** [awslabs/aws-security-assessment-solution#7]
Suggestion for the section Deployment Guide and file how-to-deploy.md

- Go to Upload files to S3 section
- Modify/update the first sentence to this :
"Copy the uncompressed files from "CloudFormation-Templates" **_to root_** directory into your S3 bucket.

Reason behind this is if you copy via folder directory and when you run CFN template it will show S3.Access denied error as the CFN would not able to find the files it is looking for as it would be looking for them in root directory.

**Comment by aws-brad** [comment]
Hello,
  Thank you for the feedback, in this case we feel this would redundant to the instructions.  As there is no other directory in your newly created bucket, it would mean it must be the root.  Additionally in the example in the block below that line, we provide an example of expected path.  

https://github.com/awslabs/aws-security-assessment-solution/blob/master/docs/how-to-deploy.md#user-content-example
