### ISSUE TITLE
had problems with html report for prowler

### ISSUE THREAD

**Issue by azandaki** [awslabs/aws-security-assessment-solution#8]
to resolve i modified the SelfServiceSecEC2.yml , added the below after line 48

          ./prowler -M html
          aws s3 cp --recursive ./output/ s3://${SelfServiceSecS3Bucket}

**Comment by aws-brad** [comment]
Hi there, can you add some more data on the issue, I didn't see any issue with the report.  Is the file not being copied on your side?

**Comment by azandaki** [comment]
Hello,
Everything would run, however no output report file is found, only a text file that's hard to read from what i can remember, after adding the above on live 48 it generated a proper html report, I followed all steps in deployment but still.

PS: I completely missed the notification of your comment back in November! so sorry!
